### PR TITLE
Civilian fleeing

### PR DESCRIPTION
**Pull request by diwako**
Adds an option to make civilians flee in a panicked animation. They will be trying to find the nearest house to hide near or even in it.
There is a 25% chance that a civ is not affected by a firefight.

Added an option into `cfg_mission` to disable this behavior, it is enabled by default

### CODE REVIEW

**Review by Liquidtracer — COMMENTED** [review]
I like the thematic situation this feature brings, my concern would come from a mission design perspective. If I wanted to have this on and have hostages or HVT's, how do they react when in a tied up state? and Is it possible to exclude specific units from the script? for example, a particularly brave ex-military civ or an agent that won't flee? Thinking for when using Civs as objectives etc

**Comment by diwako** [comment]
Actually good point, lemme add something like a variable on a unit to make it not affected. As well add support for ACE captive.

**Comment by diwako** [comment]
Support for ace captive added.

it is possible to make selected civilian immune to the feature when adding the variable `lmf_ai_civ_cannotPanic` with value true to them.
 e.g. this setVariable ["lmf_ai_civ_cannotPanic",true] in init field

**Review by G3rrus — APPROVED** [review]
Had a look at it, seems to work solidly.

**Review by Alextwokay — APPROVED** [review]

**Pull request merged**
